export default [
  {
    id: 1,
    type: "coffee",
    title: "Americano",
    description:
      "Proident reprehenderit exercitation consequat adipisicing amet ex excepteur id in.",
    price: 99,
    image: "americano",
  },
  {
    id: 2,
    type: "coffee",
    title: "Capuccino",
    description:
      "Tempor consectetur reprehenderit sit nostrud aliqua ullamco incididunt et veniam aliquip.",
    price: 199,
    image: "capuccino",
  },
  {
    id: 3,
    type: "coffee",
    title: "Macchiato",
    description: "Anim id minim veniam consectetur.",
    price: 249,
    image: "macchiato",
  },
  {
    id: 4,
    type: "coffee",
    title: "Espresso",
    description: "Anim id minim veniam consectetur.",
    price: 249,
    image: "espresso",
  },
  {
    id: 5,
    type: "coffee",
    title: "Mocha",
    description: "Anim id minim veniam consectetur.",
    price: 249,
    image: "mocha",
  },
  {
    id: 6,
    type: "coffee",
    title: "Latte",
    description: "Anim id minim veniam consectetur.",
    price: 249,
    image: "latte",
  },
  {
    id: 7,
    type: "tea",
    title: "Vanilla Tea",
    description: "Anim id minim veniam consectetur.",
    price: 249,
    image: "vanilla-tea",
  },
  {
    id: 8,
    type: "tea",
    title: "Green Tea",
    description: "Anim id minim veniam consectetur.",
    price: 249,
    image: "green-tea",
  },
  {
    id: 9,
    type: "tea",
    title: "Iced Tea",
    description: "Anim id minim veniam consectetur.",
    price: 249,
    image: "iced-tea",
  },
  {
    id: 10,
    type: "juice",
    title: "Orange Juice",
    description: "Anim id minim veniam consectetur.",
    price: 249,
    image: "orange-juice",
  },
  {
    id: 11,
    type: "juice",
    title: "Apple Juice",
    description: "Anim id minim veniam consectetur.",
    price: 249,
    image: "apple-juice",
  },
];
